package com.offbynull.rfm.host.services.h2db;

import com.offbynull.rfm.host.model.requirement.HostRequirement;
import com.offbynull.rfm.host.model.requirement.Requirement;
import com.offbynull.rfm.host.parser.Parser;
import static com.offbynull.rfm.host.services.h2db.InternalUtils.flattenRequirementHierarchy;
import static com.offbynull.rfm.host.services.h2db.InternalUtils.getRequirementChildren;
import static com.offbynull.rfm.host.services.h2db.InternalUtils.getRequirementHierarchy;
import static com.offbynull.rfm.host.services.h2db.InternalUtils.getRequirementKey;
import static com.offbynull.rfm.host.services.h2db.WorkerSearcherSql.filterByCachedCountAndCapacity;
import static com.offbynull.rfm.host.services.h2db.WorkerSearcherSql.filterByWhereCondition;
import static java.util.Collections.EMPTY_LIST;
import static java.util.Collections.EMPTY_MAP;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import static java.util.stream.Collectors.joining;
import org.apache.commons.collections4.MultiValuedMap;
import org.apache.commons.lang3.Validate;

final class WorkerSearcher {
    private WorkerSearcher() {
        // do nothing
    }
    
    public static void main(String[] args) {
        Parser parser = new Parser(EMPTY_LIST, EMPTY_LIST);
        HostRequirement hr = parser.parseScriptReqs(EMPTY_MAP, ""
                + "[1,5] host {"
                + "  1 socket where socket.s_brand==\"intel\" {"
                + "    2 core where !core.b_hyperthread {"
                + "      [2,999999] cpu 100000 capacity where cpu.b_avx==true && socket.s_model==\"xeon\" { }"
                + "      1 cpu 5000 capacity where socket.s_model==\"haswell\" { }"
                + "    }"
                + "  }"
                + "  1 gpu with 1 capacity { }"
                + "  1 mount with 256gb capacity where b_rotational==true" // for saving work
                + "  1 mount with 32gb capacity where b_rotational=false" // for temp storage
                + "  1 ram with 64gb capacity where ram.n_speed>=3000 && ram.s_brand==\"samsung\" { }"
                + "}");
    }
    
    private static Query generateQuery(HostRequirement hostRequirement) {
        Validate.notNull(hostRequirement);
        
        // get hierarchy of hostRequirement, NOT INCLUDING hostRequirement itself
        //   we don't include hostRequirement because we don't want the query generated by filterByCachedCountAndCapacity() to take in the
        //   host count -- the count and capacity is PER host.
        Set<Requirement> parentRequirements = new HashSet<>(getRequirementChildren(hostRequirement).values());
        MultiValuedMap<Requirement, Requirement> requirementHierarchy = getRequirementHierarchy(hostRequirement);
        requirementHierarchy.remove(hostRequirement);
        
        // get host key -- s_host and n_port as of now, but done dynamically so this code will continue working if it changes
        Set<String> hostKey = getRequirementKey(hostRequirement);
        
        // generate query
        QueryTracker qt = new QueryTracker();
        String queryStr = ""
                + "SELECT " + hostKey.stream().collect(joining(",")) + "\n"
                + "FROM\n";
        
        
        String nextId = qt.alias();
        Query nextQuery = filterByCachedCountAndCapacity("worker", parentRequirements, requirementHierarchy);
        queryStr += ""
                + "(\n"
                + nextQuery.compose(2, qt)
                + "\n) " + nextId;
        
        for (List<Requirement> requirementChain : flattenRequirementHierarchy(hostRequirement)) {
            String lastId = nextId;
            String _nextId = qt.alias(); // hack so nextId can be used in lambda below (can't assign to nextId directly)
            
            nextQuery = filterByWhereCondition(requirementChain);
            queryStr += ""
                    + "\n"
                    + "INNER JOIN\n"
                    + "(\n"
                    + nextQuery.compose(2, qt)
                    + "\n) " + _nextId + "\n"
                    + "ON " + hostKey.stream().map(k -> lastId + "." + k + "=" + _nextId + "." + k).collect(joining(" AND "));
            
            nextId = _nextId;
        }
        
        Query query = new Query(queryStr, qt.params());
        return query;
    }
}
